name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.11]


    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD:  ${{ secrets.DATABASE_PASS }}
          MYSQL_DATABASE: try
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
        SECRET_KEY:  ${{ secrets.DJANGO_SECRET_KEY }}
        DBENGINE: django.db.backends.mysql
        DATABASE_NAME: try
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        DATABASE_HOST: 127.0.0.1
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY:  ${{ secrets.DJANGO_SECRET_KEY }}
        DBENGINE: django.db.backends.mysql
        DATABASE_NAME: try
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        DATABASE_HOST: 127.0.0.1
    - uses: actions/checkout@v2
    - name: deploy to vm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd django-job-search
            git pull
            source my_app_venv/bin/activate
            uwsgi -d --ini uwsgi.ini
